### ISSUE TITLE
What are the TOP 5 features

### ISSUE THREAD

**Issue by mariodavid** [mariodavid/cuba-component-data-import#1]
Let's talk about what the TOP 5 features and the most common use cases for this component would be.

**Comment by mariodavid** [comment]
here's my list of stuff that seems to be most valuable:

1. ad-hoc import via UI without coding and dynamic configuration of properties-to-columns
2. pre-configured import configuration that will be selected when importing so that the configuration does not have to be made everytime
3. define importer classes that will do complex import logic (like lookup of reference data e.g.) which will not be in the configuration in the first phase and act as an escape path

**Comment by aleksey-stukalov** [comment]
From my understanding  1 and 2 should happen automatically, as I see importer itself as a set of Entities and Screens with the ImportAPI service implementation on the server side. So, you create an importer - means you use screens to input data and persist it in the data model of the importer. Then you can run it using the common interface. Is that clear?

**Comment by mariodavid** [comment]
> From my understanding 1 and 2 should happen automatically, as I see importer itself as a set of Entities and Screens with the ImportAPI service implementation on the server side

correct. I just wanted to document on what to focus. Having this building main areas of stuff that we can work on, we know what issues to create, that describe this parts in more detail.

There might be other stuff, that might important as well and I wanted to make sure, we don't forget on a very important topic.

**Comment by aleksey-stukalov** [comment]
I agree with the items, let me generally list a few points:
1. Importer component should give an infrastructure and API to be able to add importers in the project, that uses the component
3. In fact, importer is an annotated server-side bean that can import data
4. It should implement a very simple, but probably the most useful generic importer from a csv
> via UI without coding and dynamic configuration of properties-to-columns

**Comment by pfurini** [comment]
Hi,
I'll add another important point, that I've developed in my client side importer tool (https://www.cuba-platform.com/discuss/t/component-to-facilitate-import-export-data-with-external-file/2306/7?u=pfurini):

- Ability to recover the import process in the case of failure, and adding the ability to stop the import, and restart it at the point it was interrupted

**Comment by mariodavid** [comment]
Hi @pfurini, 

Can you elaborate on what you meam by stop & start later? Is that only in case of errors happening while import. In case: what should the user do after stopping it?

Bye
Mario

**Comment by pfurini** [comment]
Hi
Yes it's mainly in case of import errors, but also for partial imports.
If the import operation happens in a transaction, then the whole import
fails or succeed.
But there are situations where an atomic import is not feasible or wanted.
I usually let the user choose between the two modes.
In the case of non transactional imports, I create a log that associates
each import record with its outcome. The log can be exported as a file, so
if the import process had some errors, or it was interrupted, the user can
resubmit the same import file along with the log, and the system knows
which records to process.
Usually, even for non transactional imports, each import record is
processed inside a transaction, if it spans multiple related entities. The
order of the inserts is determined by the metadata, so there should never
be a foreign key violation.

Hope this clarifies my previous comment.
Paolo

Il giorno 7 aprile 2018 @ 15:10:39, Mario David (notifications@github.com)
ha scritto:

**Comment by mariodavid** [comment]
I'll try to unpack that a little bit for myself here :)

> I usually let the user choose between the two modes.
this is a good point. Currently i'm using the CUBA build in `EntityImportExportAPI` in order to do the actual import once the entities are parsed.
This commits all Entities in a single transaction. But i see your point on don't let the library dev decide but rather let the app dev decide on which approach to go. Actually it can be selected on an `ImportConfiguration` basis. 

> I create a log that associates each import record with its outcome.
A log is already implemented by @aleksey-stukalov but it is not really used with the new approach of the wizard. I'll will be used in the next features more and more...

>  The log can be exported as a file, so if the import process had some errors, or it was interrupted, the user can resubmit the same import file along with the log, and the system knows which records to process.

This is a pretty heavyweight implementation (especially implementation wise :)). Let's take that aside for now. 

I think for now the different import strategies should be built. I've created a issue for that: #18

**Comment by mariodavid** [comment]
Will close this for now as i have a good enough idea to create further, more concrete requirements.
