### ISSUE TITLE
ERROR:  syntax error at or near "null"

### ISSUE THREAD

**Issue by innovaringenieria** [mariodavid/cuba-component-data-import#103]
This error occurs in postgres when the tables do not exist
ERROR:  syntax error at or near "null"
LINE 1: ...RT_ATTRIBUTE_MAPPER alter column ENTITY_ATTRIBUTE set null ;

tomcat
make-entity-attribute-nullable-for-import-attribute-mapper.sql
ERROR: syntax error at or near "null"

the correct syntax would be
alter table DDCDI_IMPORT_ATTRIBUTE_MAPPER alter column ENTITY_ATTRIBUTE drop not null;

Nelson F.

**Comment by mariodavid** [comment]
Hi Nelson,

thanks for pointing out. It is solved in #105.

Will be released in 0.5.0 together with CUBA 6.9 support.
