### ISSUE TITLE
Error initializing application using data-import together with attachable component

### ISSUE THREAD

**Issue by innovaringenieria** [mariodavid/cuba-component-data-import#120]
Error initializing application
org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [de/diedavids/cuba/dataimport/web-spring.xml]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'ddcdi$WithImportBean' for bean class [de.diedavids.cuba.dataimport.web.action.WithImportBean] conflicts with existing, non-compatible bean definition of same name and class [de.diedavids.cuba.taggable.web.action.WithTagsBean]

**Comment by mariodavid** [comment]
hi,

thanks for pointing out. This is solved in 0.4.2 of attachable - https://bintray.com/mariodavid/cuba-components/cuba-component-attachable/0.4.2

Bye
