### ISSUE TITLE
initial values for entity attributes

### ISSUE THREAD

**Issue by tarekghonamy** [mariodavid/cuba-component-data-import#123]
Ability to insert a hidden column in the loader configuration that have a default value that should be programmaticly set, for example if i have have a an entity named Employee, with an attribute called employeesGroup, the EmployeesGroup is the master entity of the Employee, when a user imports employees he first selects a particular EmployeeGroup in the master and then click the import button for the employees.

**Comment by mariodavid** [comment]
hi,

this is not possible currently. But what you can do is to define default values through a [pre-commit script](https://github.com/mariodavid/cuba-component-data-import#pre-commit-script).

But what is currently not possible is to dynamically inject the values into the execution of the import process...

What would you think on how to inject this data into the import process?

**Comment by tarekghonamy** [comment]
Hi Mario,

i am not quite sure now, i am starting the data import function in my app after 1 week, i will be trying various stuff including injecting columns, I have noticed some error that the data import addon is not compatible with 6.10 but i didn't upgrade yet.

**Comment by tarekghonamy** [comment]
Hi Mario, i have recently upgraded to 6.10.2, i was hoping to start with data import straight away but the the data import add-on is not compatible with 6.10. any idea when you can upgrade the data import add-on.

**Comment by mariodavid** [comment]
hi, 

as always in case of a CUBA version update: you generally can ignore the studio warnings regarding not matching versions. Generally it just works.

bye

**Comment by mariodavid** [comment]
hi @tarekghonamy 

I just released 0.7.0 which contains support for CUBA 6.10.

Bye
Mario

**Comment by mariodavid** [comment]
hi,

the dynamic default values are implemented in version 0.8.0. See README for more details: https://github.com/mariodavid/cuba-component-data-import#withimportwizard-interface-for-browse-screens-cuba-7-standardlookupt
