### ISSUE TITLE
MySQLSyntaxErrorException: Unknown column 'ASSOCIATION_LOOKUP_ATTRIBUTE' in 'field list'

### ISSUE THREAD

**Issue by avifatal** [mariodavid/cuba-component-data-import#133]
Hi David.
I have a few questions if I may.
1. When I want to save the configuration, after the import is done, I get the exception `MySQLSyntaxErrorException: Unknown column 'ASSOCIATION_LOOKUP_ATTRIBUTE' in 'field list'`.

2. I have installed via the studio and never got the SQL create tabled scripts, so I took it manually from the git repository.

3. Can I import programmatically? I generate environment via Test method, and I want to import config via your tool while generating the env.

4. I want to import roles and permissions, how can I export them together so will be able to import them together.

Thanks.

**Comment by mariodavid** [comment]
hi,

1. did you check the DB table `DDCDI_IMPORT_ATTRIBUTE_MAPPER` and looked for the `ASSOCIATION_LOOKUP_ATTRIBUTE` - does it exists?

2. What does that mean in the concrete? How did you install it etc.

3. You can. The plugin is not optimized currently to be used in this way. The starting point for you should be [GenericDataImportService](https://github.com/mariodavid/cuba-component-data-import/blob/master/modules/global/src/de/diedavids/cuba/dataimport/service/GenericDataImporterService.java).

4. Why do you not do it directly via the entity inspector export / import facility? I mean it would probably work via this plugin as well (although compositions are not super duper supported). However, this plugin is more for integration use cases like: the business has some excel sheets from previous business processes and this unstructured files need to get imported.

**Comment by avifatal** [comment]
Hi, Sorry for the delay, Did not get the notification.

1. The attribute is not presented in the table. maybe I took the wrong version from your github. But yet again, the plugin was supposed to create the tables it self.

2. I have installed it as the tutorials said.  Via "Project Properties".

3.  Ok.

4. Ok. I did not know that. I will dig into this.

Thank you
