### ISSUE TITLE
Contraint violation

### ISSUE THREAD

**Issue by skerain** [mariodavid/cuba-component-data-import#146]
Hello,

1. Configure an import via import wizrd
2. Import processed, i want to quit: constraint violation on sys_file (duplicate)

I've tried several times with purge of sys_file (drop cascade) but no way.
TRUNCATE TABLE sys_file CASCADE;

OpenJDK 11, Cuba 7.2-SNAPSHOT, PostgreSQL 10.6

Tried with Cuba 7.0.10: same result.

It's seems to appear when I try to save the configuration for later use.

[caub-constraint-violation.log](https://github.com/mariodavid/cuba-component-data-import/files/3541080/caub-constraint-violation.log)

**Comment by mariodavid** [comment]
closed due to this comment: https://www.cuba-platform.com/discuss/t/data-import-cant-save-unique-configuration/9438/7?u=mario
