### ISSUE TITLE
Support for Dynamic Attributes

### ISSUE THREAD

**Issue by ryanswidmer** [mariodavid/cuba-component-data-import#48]
Mario,

Thank you for providing a valuable component to the community. I'm currently not able to set a category and dynamic attribute on an imported entity. Is this not supported and if not, do you plan to?

Thanks!

**Comment by mariodavid** [comment]
Hi,

Thanks for reaching out. Currently dynamic attributes are not supported. But it makes sense to have it.

Can you provide an example file and dynamic attribute config for mlbteam entity in this project: https://github.com/mariodavid/cuba-component-data-import-tests

Just download it, add your dynamic attribute, put the SQL for the config in 30.create-db.sql. then add an example excel / csv file in the example-data dir and run the zipProject gradle task. You can upload the reault here and i will take a look.

Thanks

**Comment by mariodavid** [comment]
Hi @ryanswidmer,

dynamic attributes support is implemented in #60 and will be available in the next release 0.3.0
