### ISSUE TITLE
Idea of UI for importing

### ISSUE THREAD

**Issue by mariodavid** [mariodavid/cuba-component-data-import#5]
I imagine that something it is working in Excel could be some potential end goal:

![Excel Import example](https://support.teamgate.com/hc/en-us/article_attachments/202141452/csv_2GIF.gif)

We could try to come up with UI sketches that will guide us on where the feature-set as well as the implementation should go.

**Comment by aleksey-stukalov** [comment]
We could develop the following behaviour:
1. Pick master entity e.g. Car.class
2. Map columns respectively to this master entity: 

| Destination        | Source      | Alias           |
-----------------|-----------|-------------
| {E}.driver.name | column 5  | firstName    |
| {E}.car.plate       | column 1  | regNumber |
....
3. Define policy for searching if entity already exists with its behaviour

| Entity              | Unique Index                        | Policy if exists   (leave, re-write, create new) |
--------------|----------------------------|-------------------
| Car.class      | regNumber                            | re-write if exists  |
| Driver.class | firstName, secondName,...  | leave if exists       |
...
4. Define column for EOF detection (when meeting first empty cell in it)
5. Define map of default values

**Comment by mariodavid** [comment]
Yeah, this sounds good. 
1. could be either done via: giving the master entity as a parameter, or make it the first step of the wizard. Probably both should be supported.
2. Yeah, i don't know how the UI should look like. Additionally we should start small with direct String / int attributes. Then we take in ENUMS, then associations or something.
3. I don't really know what you mean. Can you elaborate?
4. this is Excel specific, right? For CSV it would be options like "seperator" e.g.
5. might make sense. Perhaps also not 0.1.0, but sounds good.

**Comment by aleksey-stukalov** [comment]
3 - reading a line you need to see if you already have this record in the database. And if yes, what should be done? Should data be re-written? Should it be left as is with no action? Should be created a new similar row? E.g. in [this case](https://github.com/mariodavid/cuba-component-data-import/blob/fc86b88a542ff5e29bd475db834e16196863a760/modules/core/src/de/diedavids/cuba/dataimport/core/example/CustomerImporter.java#L80-L95) if customer exists we will update all the fields of it to what is specified in the importing file
4 - yes, you are right
5 - map of defaults is extremely useful, and already developed (see [here](https://github.com/mariodavid/cuba-component-data-import/blob/fc86b88a542ff5e29bd475db834e16196863a760/modules/core/src/de/diedavids/cuba/dataimport/core/example/CustomerImporter.java#L61-L65)). So, if you cannot parse something, or you have an empty value for a mandatory attribute, then you simply apply defaults.

**Comment by mariodavid** [comment]
Alright - so I implemented the first version. Mainly it was with CSV in mind, but I have already the XSLX in mind :)
![import-wizard-draft](https://user-images.githubusercontent.com/817400/38327673-16d35226-3849-11e8-9bc1-8f5dbd1ccf0e.gif)

The current wizard has the following steps:

1. upload file
2. select entity
3. setup columns <-> attributes
4. extended import configuration
5. preview

The following features are not included in the first draft:

* setup default values
* support for boolean type
* references to other entities
* preview on the parsed data instead of the raw csv data
* feedback if import was not successful
* a lot of other stuff


Let's talk about it ;)

**Comment by aleksey-stukalov** [comment]
Looks great!

Form my experience it would be also great to be able to define some kind of transformation script for each column right at step 3 and remove step 4. So, you can (or must for associations attributes or enum types) define a groovy script where you have _value_ as the parameter, then you transform it into the right output format.

What do you think about it? From my perspective, this would make the applicability of such importer much wider.

P.S. We also can have prefined scripts for Integers, Doubles, Dates and other widely used types, to convert the value into the corresponding format.

**Comment by aleksey-stukalov** [comment]
Another improvement I see is an ability to save upload scenario and re-use it later.

**Comment by aleksey-stukalov** [comment]
> But it is questionable, which people will mainly use that wizard. Is it a developer? In this case, this feature makes total sense. Is it an end user / administrator? Than this feature will scare people away. Therefore i think we should try to build the main use cases (enum matcher, lookup of another entity by ID / another column etc.) that into the wizard.

Again, from my experience users will mess everything up using such tool. So, I would say it will be an administrator. As for searching by id - this is never the case in the real world. Did you see tables for import with uids from your system in it :)? 

At the same time writing a simple script is not a big problem for anyhow educated administrator, e.g. 
`
if (value.equals("high"))
    return Priority.HIGH
else  
    return false
`
Plus, for all non-string types of attributes, we can have default transformation scripts, like for an int field it would be like:
`
Integer.valueOf(value)
`

**Comment by mariodavid** [comment]
> As for searching by id - this is never the case in the real world. Did you see tables for import with uids from your system in it :)?

Obviously not by ID in case of a UUID. But sometimes it might be a auto increment ID and then it might actually be the case... Whatever - the main point is here to select an association by an attribute of that association. Example:

`MlbPlayer` N:1 `MlbTeam` through the attribute `team`. Now `MlbTeam` has attributes `name` and `code`.

In the CSV file there is a reference to `team` and it contains the `code` of the MlbTeam entity.

This is a fairly easy case and it should just work out of the box. The equivalent in Excel is [vlookup](https://exceljet.net/excel-functions/excel-vlookup-function) :)

Here's the full example:

<img width="967" alt="bildschirmfoto 2018-04-05 um 12 30 03" src="https://user-images.githubusercontent.com/817400/38361411-8821b2cc-38cd-11e8-8115-ba0074727360.png">

<img width="685" alt="bildschirmfoto 2018-04-05 um 12 33 03" src="https://user-images.githubusercontent.com/817400/38361405-83e879d4-38cd-11e8-911e-5a5d637ce65d.png">

I updated the MLB example in the code...

**Comment by mariodavid** [comment]
> 3 - reading a line you need to see if you already have this record in the database. And if yes, what should be done? Should data be re-written? Should it be left as is with no action? Should be created a new similar row? E.g. in this case if customer exists we will update all the fields of it to what is specified in the importing file

@aleksey-stukalov , you wrote that above that stated it `Unique Index` in the table (https://github.com/mariodavid/cuba-component-data-import/issues/5#issuecomment-367265305). But this is not a unique constraint that should get introspected by the application, but rather something that can be defined by the user, right?
So the user says "if Driver.firstname + Driver.lastname in this combo already exists, then do nothing / replace / update etc." - correct?

This would require that actually every data row will some amount of queries to the DB. But it sounds reasonable...

**Comment by aleksey-stukalov** [comment]
> @aleksey-stukalov , you wrote that above that stated it Unique Index in the table (#5 (comment)). But this is not an already existing DB unique constraint that should get introspected by the application, but rather something that can be defined by the user, right?

Right, this is some kind of business-key, some set of columns, that specify unique of a record.

> This would require that actually every data row will some amount of queries to the DB. But it sounds reasonable...

Yes, but there is no other way...

**Comment by mariodavid** [comment]
ok then - i understand. Created a story for that:
https://github.com/mariodavid/cuba-component-data-import/issues/20

**Comment by mariodavid** [comment]
Will close this issue now, as we have a solid understanding of how the wizard should look like.
Follow up issues will come in order to improve.
