### ISSUE TITLE
Import of inherited entities

### ISSUE THREAD

**Issue by kechkibet** [mariodavid/cuba-component-data-import#68]
Hi,
There seems to be a bug on import of inherited entities. The importer picks the class for the parent entity  instead of the entity i am trying to import, when i change the mapping to be the inherited, i get 0 imports.
Is it possible to cast the entity to the type on the dropdown?

**Comment by mariodavid** [comment]
Hi @kechkibet ,

thanks for reaching out. I have not tried entity inheritance together with this app component at all (and to be honest hadn't that in mind while implementing), so everything might happen basically :)

Can you share a little bit more concrete what you tried? Perhaps you can give me an example app with the domain model together with the import file. Then I can also try it out on my own.

Thanks
Mario

**Comment by kechkibet** [comment]
Hi,
Sorry for the late response, this is there screen shot :
<img width="1412" alt="importerror" src="https://user-images.githubusercontent.com/1642479/39956563-d8af74b4-55eb-11e8-839c-773fe0975f0e.PNG">

As you can see, i selected the revenue streams which extends the country revenue but the importer picks county revenue instead of what i have selected.

**Comment by mariodavid** [comment]
Hi,

can you update to 0.3.0? The UI marker on the right I updated to just use the attribute name directly. Besides this UI glitch, does it have any other implications? I did not fully understand what exactly goes wrong.

Can you please share an example? Thx

**Comment by kechkibet** [comment]
this seems fixed by release 0.3.0, i am gonna close this for now.
