### ISSUE TITLE
Import Configuration : handle error message when file uploaded doesn't correspond

### ISSUE THREAD

**Issue by genthalili** [mariodavid/cuba-component-data-import#78]
From Import Configuration browser
When user Imports a file based on a selected configuration
**Issue :** 
If the file uploaded is not corresponding with Template/attribues mapper and there is a MissingPropertyException: <field> Unexpected Error.
**To fix :** 
Detect un-matching uploaded file and inform kindly the user that there is a conflict.

**Comment by mariodavid** [comment]
done in #99
