### ISSUE TITLE
Creating Import Configuration from Template with unmatching attributes

### ISSUE THREAD

**Issue by genthalili** [mariodavid/cuba-component-data-import#80]
When creating a new **Import Configuration** with a **Template**, there is an error if the column are not matching (can not bind)...
In this case the `ATTRIBUTE_TYPE` will be null and as such will throw a SQLServerException...
This happens when your template is completely different from the parameters.. which might happen

Can we change this by setting a default attributes or maybe updating the UI of create with something similar to  the Wizard AttributeMapper table ?

**Comment by mariodavid** [comment]
i have relaxed the constraints on the import attribute mapper. It can be null now. Will be handled downstream...

done in #82
