### ISSUE TITLE
Datatype binding issues in case of Association Lookup

### ISSUE THREAD

**Issue by genthalili** [mariodavid/cuba-component-data-import#85]
In Association, binding throws an error because of String <> Integer type.
String is on the file (a number imported is considered as string ex: `14` in the file), and the association attribute is an Integer, then when it's looking for a lookup it fails...

**Comment by mariodavid** [comment]
can you give me a concrete example on that?

This might be a bigger issue, but i want to make sure I understand correctly...

**Comment by genthalili** [comment]
I dont have a code example, but to make it simplier : 
when you do property search for an foreign entity (lookup), then if the attribute is Integer in the database this will throw an exception, because file is considering everything as string.
When you send the value attribute to the Association binding, it needs to do the right conversion before performing a loadbyproperty(... **Object** value ...)

**Comment by mariodavid** [comment]
done in #129 - released in 0.6.0
