### ISSUE TITLE
Error adding component in studio 6.9

### ISSUE THREAD

**Issue by innovaringenieria** [mariodavid/cuba-component-data-import#98]
Can't find the repository to download 'declarativecontrollers-global-0.5.0.pom'
Nelson F.

**Comment by aleksey-stukalov** [comment]
Hi @innovaringenieria ,

Please find in [this repo](https://github.com/balvi/cuba-component-declarative-controllers).

Regards,
Aleksey

**Comment by genthalili** [comment]
Hi @innovaringenieria , 
It normally it should find it https://dl.bintray.com/balvi/cuba-components/de/balvi/cuba/declarativecontrollers/declarativecontrollers-global/0.5.0/

Check if you haven any issue with the proxy or firewall.

**Comment by mariodavid** [comment]
relates to #102

**Comment by mariodavid** [comment]
done in #104
